### ISSUE TITLE
not using flume?

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-unread#4]
When I load this plugin I get a folder `.ssb/unread` on my system. All of the newer plugins I know of have been ported to `.ssb/flume/$plugin`.

Not really an _issue_ just wondering why / what is going on.

**Comment by dominictarr** [comment]
I think this doesn't go in flume because it's not a _view_ (i.e. it's not generated from the messages) it's just stored directly as database records that records what you have read. If it was to be a flume view, you'd need to post messages about whether you read a given message.
